src/usr/bin/google_set_multiqueue
When the number of CPUs is above 32, affinity string must be in the form: "high-order-dword,low-order-dword", but in fact it was 'low-order-dword,low-order-dword', causing "Value too large for defined data type" errors.
Changes done to fix this:
* Add missing bit shift operator
* Take care of the endianess
=> Fix tx affinity logic when number of CPUs is above 32

src/lib/udev/rules.d/65-gce-disk-naming.rules
The current rules only allow for symlinks of up to 8 local SSD disks,
and also rely on the NVMe controller for the local drives being labeled
as nvme0*.  This updates the rule to check for the appropriate
model name "nvme_card", which always corresponds to the local SSD
controller, rather than relying on the device name.
The additional PROGRAM element is required to 0-index the nsid so
that this change doesn't alter the expected symlinks (a value of 0 for
a namespace ID is invalid according to the spec).
=> Updates the udev rules for local SSD disks.

packaging/debian/control, packaging/google-compute-engine.el6.spec, packaging/google-compute-engine.spec, src/lib/udev/google_nvme_id, src/lib/udev/rules.d/64-gce-disk-removal.rules, src/lib/udev/rules.d/65-gce-disk-naming.rules
This PR adds additional udev rules and a script to support disk identification for PD NVMe disks.  
It requires the nvme-cli tool (updated in package configurations) and a specific vendor extension to the NVMe device/controller.  The disk name will be present in this field (along with some other metadata).
It was tested in the following configurations:
- Devcluster with multiple NVMe disks attached (symlinks created including links for specific partitions)
- Staging & Devcluster with missing nvme-cli tool (boot successful but no symlink, which is expected)
- Staging with missing vendor extension (boot successful and no symlink, which is expected)
=> Updated udev rules

src/lib/udev/rules.d/65-gce-disk-naming.rules
udev substitution rules support both % and $ syntax, so the `$(())` arithmetic syntax here is first attempted as a udev substitution and fails with a warning. it has no apparent impact beyond the warning, udev falls back to sending the not-substituted text.
Fixes: #14
=> correct udev rule syntax

src/etc/dracut.conf.d/gce.conf
In Fedora 33, this config file causes the warning:
```
dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file.
```
When executing `dracut --force` in `%post`
=> dracut.conf wants spaces around values

src/usr/bin/google_set_hostname
improve the metadata exploit detection
* use grep for case insensitive matching
* wrap actions in conditions rather than exiting
the script is sourced rather than executed on some systems, and this will cause 'exit 0' to promulgate to the sourcing function, causing a premature exit and leaving the system unconfigured.
=> use grep for hostname check

packaging/debian/control, packaging/debian/install, packaging/google-compute-engine.spec, src/etc/rsyslog.d/90-google.conf, src/usr/bin/google_set_hostname
* Set hostname entry to always use 127.0.0.2
* Remove all rsyslog-related code except for the exit hook restart
* Don't care if nmcli or rsyslog restart fail (this script must not fail)
=> dont set IP in etc/hosts; remove rsyslog

packaging/debian/control, packaging/debian/install, packaging/google-compute-engine.spec, src/etc/rsyslog.d/90-google.conf
Partial rollback of #26 where we tested building without rsyslog. Seems we want to keep it around for now.
=> restore rsyslog

src/usr/bin/google_set_hostname
It prevents restarting network and rsyslog when it's not actually required.
=> dhcp hostname: don't reset hostname if the hostname hasn't changed

src/lib/udev/google_nvme_id, src/lib/udev/rules.d/65-gce-disk-naming.rules
Two changes have been included in this commit:
1. Extended `google_nvme_id` script to handle local SSD devices and support multiple controllers for local SSD.
2. Updated udev rules for local SSD in 65-gce-disk-naming.rules
=> Support multiple local SSD controllers.

src/usr/bin/google_set_hostname
The guest system may have its static hostname set with fully qualified hostname, this change make sure to only reset hostname if the static hostname is not fully qualified name and is different to the truncated new_host_name.
=> set hostname: consider fully qualified static hostname

src/lib/udev/rules.d/65-gce-disk-naming.rules
We would like to ship these rules in Fedora CoreOS and RHEL CoreOS. In these image-based systems, we ship the exact same content to cloud and bare metal platforms alike.
The way these rules are written currently, they assume that the host is running in GCP and so create symlinks for all SCSI and NVMe disks and partitions. This conflicts with our image model.
We could play some tricks on the OS side so that the rules are only activated in GCP, but it would be simpler if they were written in the first place to tolerate running outside GCP.
Even on traditional Linux distros, users may mistakenly install the package containing these rules and be surprised to find `google` symlinks show up.
Tweak the rules to skip symlinking if it's not a Google device.
For SCSI disks, we can rely on the …
=> src/lib/udev: only create symlinks for GCP devices

packaging/google-compute-engine.spec, src/lib/dracut/modules.d/30gcp-udev-rules/module-setup.sh
- The dracut module is required for ignition (https://github.com/coreos/ignition) to work when using Redhat/Fedora CoreOS in GCP. Since the rules are kept in this repository, makes sense for the module to be part of it as well for a better maintenance in case the rules change;
- Modify the spec file to include the new dracut module.
=> dracut: Add a new dracut module for gcp udev rules

src/lib/udev/google_nvme_id
This reverts commit 512f7af07185041c604c3b6d9cf9ceccb5630c7d.
The migration from xxd to cut broke some distros i.e debian. The migration is either incorrect or backward incompatible.
=> Revert "Replace `xxd` to `cut` for google_nvme_id (#49)"

packaging/debian/control
Add xxd dependency to debian packaging since google_nvme_id script has a runtime dependency to it.
=> debian packaging: add xxd dependency

packaging/debian/control, src/lib/udev/google_nvme_id
Replace xxd with dd for google_nvme_id
`google_nvme_id` script currently uses `xxd` to parse nvme device
info, but we need to install additional package `xxd` for fedora,
`vim-common` and `vim-filesystem` for centos (or rhel) before
using it. Replace it with `dd` and we do not need to install
additional packages.
See https://github.com/coreos/fedora-coreos-config/pull/2412 (comment)
We initially tried to replace it with cut, creating a different
result than expected.
See: https://github.com/GoogleCloudPlatform/guest-configs/pull/49 Discussion  about the use of `dd`vs `cut`.
Tests for Fedora CoreOS:
```
nvme id-ns -b /dev/nvme0n1 | xxd -p --seek 384 | xxd -p -r | od -x
0000000 227b 6564 6976 6563 6e5f 6d61 2265 223a
0000020 6570 7372 7369 6574 746e 642d 7369 2d6b
0000040 2230 222c 6964 …
```
=> Replace xxd with dd for google_nvme_id

src/usr/bin/google_set_multiqueue
Verified there are some docker interfaces that was not excluded from the filter, this change aim to just setup IRQ for pci devices.
=> update multinic filter to pick only pci devices

src/usr/bin/google_set_multiqueue
This PR should only change the behavior of A3+ VMs. For A3 VMs, the script should maintain the same SMP affinity binding for both IRQs and XPS.
=> Setup SMP affinity for IRQs and XPS on A3+ VMs

src/usr/bin/google_set_hostname
fixes #66 
The regexp is obviously overkill but it's correct and it makes zero new assumptions about what rsyslog looks like on the host. The current method of `grep rsyslog | cut -f1 -d' '` has a lot of edge cases, I don't want to find out later that there's some obscure setup we broke by assuming that everything is named `rsyslog.service`.
/cc @dorileo @zmarano
=> extract rsyslog service name with a regexp for valid systemd unit names

packaging/debian/install, packaging/google-compute-engine.spec, src/etc/NetworkManager/dispatcher.d/google_hostname.sh
This compat script is no longer shippped in newer versions of EL9. Tested with both scripts on the same system and the second execution just overrides the first with the same (still correct) data.
This will affect other distros that use network manager too but I don't think this should be a problem. IPv4 support only, but we can fix this later.
/cc @dorileo 
Fixes #69
=> Add hostname hook for NetworkManager without dhclient compat script

src/usr/bin/google_set_multiqueue
Update `is_a3_platform` to identify A3-edge shape to apply `google_set_multiqueue` on a3-edge VMs.
=> Update is_a3_platform to include A3-edge shape

src/usr/bin/google_set_multiqueue
This is required to enable IRQ spread for both `a3-edgegpu-8g` and `a3-edgegpu-8g-nolssd` VMs.
=> Fix the name for A3 Edge VMs

src/etc/sysconfig/network/scripts/google_up.sh, src/usr/bin/google_set_hostname
=>  Call google_set_hostname on openSUSE and when the agent is configured to manage hostname and FQDN, let it.

packaging/debian/control, packaging/ubuntu/control, src/etc/sysconfig/network/scripts/google_up.sh, src/usr/lib/networkd-dispatcher/routable.d/google_hostname.sh
This will skip executing hooks for interfaces that systemd-networkd knows about but doesn't manage, such as docker's. Adds a dependency on `jq`, if we really don't want to take a new dependency we can do something like  `grep -oE '\"[Ss]tate\"\s*:\s*"[^"]*"'` but it's a bit brittle and relies on the json not changing very much.
/cc @dorileo @ChaitanyaKulkarni28 @drewhli 
/hold
=> Always use IP from primary NIC in the networkd-dispatcher routable hook

packaging/google-compute-engine.spec
If users switch to wicked or systemd-networkd on these systems they will need it. No impact by default.
/cc @ChaitanyaKulkarni28 @dorileo @drewhli
=> Depend on jq in enterprise linux

src/usr/bin/google_set_multiqueue
Update is_a3_platform to identify a3-ultragpu-* shapes to apply google_set_multiqueue on A3Ultra VMs.
=> Update google_set_multiqueue to enable on A3Ultra family

src/usr/bin/google_set_multiqueue
On A3Ultra and A4 platforms, we will want to skip setting IRQ binding on non-gvnic devices as there will be a mixture of GVE and Mellanox drivers. This PR introduces a `is_gvnic` method which determines if the nic is gvnic or not by using the `ethtool -i <interface>` command.
=> Update google_set_multiqueue to skip set_irq if nic is not a gvnic device

src/usr/bin/gce-nic-naming
An issue with the prior behavior is that on error, we assume it is OK to use the predictable NIC name rather than allowing udev to decide what the fallback would be. When a guest configures "ethX" names and this script exits with errors, the ethX configuration is ignoring. This is particularly relevant in situations such as c3metal where we expect the script to error because we have an IDPF NIC but no accelerator devices.
/cc @dorileo @ChaitanyaKulkarni28
=> gce-nic-naming: exit 1 so that udev ignores the rule on error

src/lib/udev/rules.d/75-gce-network.rules, src/usr/bin/gce-nic-naming
IDPF is too broad a driver to trigger on so removing for the time being.
=> Remove IDPF devices from renaming rules

src/usr/bin/google_set_multiqueue
For different VM platform the vCPU count is different so the vCPU ranges for IRQ binding will be also different, this PR introduces a `get_vcpu_ranges` method to get the vCPU ranges based from sys file instead of a hardcoded range.
=> Update google_set_multiqueue to configure vCPU ranges based on VM platform

src/lib/udev/rules.d/75-gce-network.rules, src/usr/bin/gce-nic-naming
This reverts commit a528f221688831c3c48425c7d5f6b38c0a21eb8f.
Allows IDPF RDMA devices to be renamed at boot time.
=> Restore IDPF devices for renaming rules

src/usr/bin/google_set_multiqueue
Update is_multinic_accelerator_platform to check for pnic_id presence on all network-interfaces in the MDS, this should be the indication of whether the platform is a multi-nic accelerator platform from now on.
=> Update google_set_multiqueue to check pnic_ids

packaging/ubuntu/install
This reverts commit 50c546896f5643ad35c0c49453ecb9ea4c99b585.
This change introduced a regression with hostname setup where it conflicts with cloud-init use cases supported by Ubuntu.
=> Revert "Include systemd-networkd hook in Ubuntu packaging (#77)"

src/usr/bin/google_set_multiqueue
In order to support VM shapes with 64 queues, we need to unpack the IRQ ranges and pass in the list of available cores for each numa node to set_irq_range for core assignment
=> Update google_set_mulltiqueue to unpack IRQ ranges before core assignment

src/usr/bin/google_set_hostname
In cases where the metadata server /etc/hosts entry was not added by the guest environment scripts there will be no "# Added by Google" marker. As such the script will add a second reference to the metadata if it already exists. We should only have 1 entry. Respect the already existing entry and do not add a second entry.
=> Avoid duplicate entries for the metadata server in /etc/hosts

src/usr/bin/google_set_multiqueue
- the `set_irq_range` lines for core assignment contain a syntax error, which is preventing the core assignment from taking effect
- fix function name bitmapbitmap_to_rangelist -> bitmap_to_rangelist
=> Fix core assignment in set_irq_range
